/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'brand-ivory':    '#FAF8F5',
        'brand-silk':     '#F5F0EB',
        'brand-sand':     '#E8DFD5',
        'brand-taupe':    '#8C7E74',
        'brand-cocoa':    '#4A3F38',
        'brand-dark':     '#1A1614',
        'brand-night':    '#26201C',
        'brand-sage':     '#788779',
        'brand-rose':     '#CBB0A6',
        'brand-gold':     '#C5A059',
        'brand-gold-light':'#F4ECE1',
        'brand-navy':     '#0F172A',
        'brand-navy-deep':'#1B2A4A',
        'brand-slate':    '#475569',
        'brand-slate-light':'#64748B',
        'hero-bg':        '#FAF8F5',
        'card-bg':        '#FFFFFF',
        'reviews-bg':     '#F4EFEA',
        'divider-band':   '#E2D8CC',
        'btn-primary':    '#1A1614',
        'btn-navy':       '#0F172A',
        'btn-hover':      '#362E2A',
        'text-primary':   '#1A1614',
        'text-body':      '#4A423C',
        'text-muted':     '#8C827A',
      },
      fontFamily: {
        serif: [
          '"Cormorant Garamond"',
          'Georgia',
          'Cambria',
          '"Times New Roman"',
          'serif',
        ],
        sans: [
          '"Plus Jakarta Sans"',
          '"Be Vietnam Pro"',
          '-apple-system',
          'BlinkMacSystemFont',
          'sans-serif',
        ],
      },
      fontSize: {
        'display-xl':     ['68px', { lineHeight: '0.98', letterSpacing: '-0.03em' }],
        'display-lg':     ['54px', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-md':     ['40px', { lineHeight: '1.10', letterSpacing: '-0.01em' }],
        'hero-desktop':   ['58px', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'hero-mobile':    ['38px', { lineHeight: '1.08', letterSpacing: '-0.01em' }],
        'section-desktop':['36px', { lineHeight: '1.15' }],
        'section-mobile': ['28px', { lineHeight: '1.20' }],
        'body-lg':        ['18px', { lineHeight: '1.75' }],
        'body':           ['16px', { lineHeight: '1.70' }],
        'body-sm':        ['14px', { lineHeight: '1.65' }],
        'label':          ['11px', { lineHeight: '1.4', letterSpacing: '0.22em' }],
      },
      maxWidth: {
        'page': '1240px',
        'reading': '680px',
      },
      borderRadius: {
        'btn': '2px',
        'card': '4px',
        'pill': '9999px',
      },
      boxShadow: {
        'luxury': '0 20px 40px -15px rgba(26, 22, 20, 0.07)',
        'luxury-hover': '0 30px 60px -12px rgba(26, 22, 20, 0.12)',
        'glass': '0 8px 32px 0 rgba(26, 22, 20, 0.05)',
      },
      letterSpacing: {
        'editorial': '0.22em',
        'widest-plus': '0.30em',
      },
    },
  },
  plugins: [],
}
